name: Python CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  compile:
    name: Compile Python app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Compile Python app
        run: python3 -m compileall .


  build:
    name: Build package

    needs:
      - compile

    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          #cache: 'poetry'

      - name: Set up Poetry
        run: poetry env use ${{ steps.setup-python.outputs.python-path }}

      - name: Install project dependencies
        run: poetry install --no-interaction --without=dev

      - name: Build package
        run: poetry build --no-interaction

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package on PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --no-interaction

      - name: Publish a release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          name: ${{  github.ref_name }}
          generate_release_notes: true